#!/bin/bash

set -eu

here="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
swift_dir="$here/../../utf8-swift/swift"
test -d "$swift_dir" || { echo "error: swift not found in '$swift_dir'"; exit 1; }

swift_sha=$(git ls-remote -h git@github.com:milseman/swift.git refs/heads/utf8string | cut -f1)
echo "- swift sha: $swift_sha"

tmpfile=$(mktemp /tmp/.update-checkout_XXXXXX)
cat >> "$tmpfile" <<EOF
{
    "https-clone-pattern": "https://github.com/%s.git",
    "ssh-clone-pattern": "git@github.com:%s.git",
    "repos": {
        "compiler-rt": {
            "remote": {
                "id": "apple/swift-compiler-rt"
            }
        },
        "llvm": {
            "remote": {
                "id": "apple/swift-llvm"
            }
        },
        "swift-xcode-playground-support": {
            "remote": {
                "id": "apple/swift-xcode-playground-support"
            }
        },
        "swift-corelibs-foundation": {
            "remote": {
                "id": "apple/swift-corelibs-foundation"
            }
        },
        "clang": {
            "remote": {
                "id": "apple/swift-clang"
            }
        },
        "llbuild": {
            "remote": {
                "id": "apple/swift-llbuild"
            }
        },
        "cmark": {
            "remote": {
                "id": "apple/swift-cmark"
            }
        },
        "lldb": {
            "remote": {
                "id": "apple/swift-lldb"
            }
        },
        "swift-corelibs-xctest": {
            "remote": {
                "id": "apple/swift-corelibs-xctest"
            }
        },
        "ninja": {
            "remote": {
                "id": "ninja-build/ninja"
            }
        },
        "swift-integration-tests": {
            "remote": {
                "id": "apple/swift-integration-tests"
            }
        },
        "swiftpm": {
            "remote": {
                "id": "apple/swift-package-manager"
            }
        },
        "swift": {
            "remote": {
                "id": "apple/swift"
            }
        },
        "swift-corelibs-libdispatch": {
            "remote": {
                "id": "apple/swift-corelibs-libdispatch"
            }
        }
    },
    "branch-schemes": {
        "utf8string": {
            "repos": {
                "compiler-rt": "8160e45e66b631d091f9e585e38d6e5f262ec6c8",
                "llvm": "a4d539e482ca76290f3db6b775203ae230b34d42",
                "swift-xcode-playground-support": "f2e299a37eb6531918b6c9ce7f555b54d68d92d4",
                "swift-corelibs-foundation": "707896fe1041c8d9c0ed6fa4a0752100714ee793",
                "clang": "773ac0251a7ea94c0b58d96353d4210a7eb2aeef",
                "llbuild": "b1ac250308264b0f57457448cd47ac45de53df71",
                "cmark": "d875488a6a95d5487b7c675f79a8dafef210a65f",
                "lldb": "2231b516a5b8e9059d3e62b1d936bee99b6c3c38",
                "swiftpm": "eee27531dec0a8a9c509ccfa324b8c7a81c1df61",
                "swift-corelibs-xctest": "11b22e5ed8d6ffc2734810ae6d3b56160092745b",
                "ninja": "253e94c1fa511704baeb61cf69995bbf09ba435e",
                "swift-integration-tests": "e882c92e1f063f5971f11c4163414fd75356f521",
                "swift": "$swift_sha",
                "swift-corelibs-libdispatch": "5f49e8bd1403757da08a685cea9c276ccdd09b75"
            },
            "aliases": [
                "utf8string"
            ]
        }
    }
}
EOF

(
cd "$swift_dir"
utils/update-checkout --config="$tmpfile" --scheme=utf8string
)

rm "$tmpfile"

echo OK
