#!/bin/bash

set -eu

here="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
swift_dir="$here/../../utf8-swift/swift"
test -d "$swift_dir" || { echo "error: swift not found in '$swift_dir'"; exit 1; }

(
cd "$swift_dir"/..
for dir in compiler-rt llvm swift-xcode-playground-support \
    swift-corelibs-foundation clang llbuild cmark lldb swiftpm \
    swift-corelibs-xctest ninja swift-integration-tests swift \
    swift-corelibs-libdispatch; do
    (
    cd "$dir"
    git fetch > /dev/null
    )
done
)

swift_sha=$(git ls-remote -h git@github.com:milseman/swift.git refs/heads/utf8string | cut -f1)
echo "- swift sha: $swift_sha"

tmpfile=$(mktemp /tmp/.update-checkout_XXXXXX)
cat >> "$tmpfile" <<EOF
{
    "https-clone-pattern": "https://github.com/%s.git",
    "ssh-clone-pattern": "git@github.com:%s.git",
    "repos": {
        "compiler-rt": {
            "remote": {
                "id": "apple/swift-compiler-rt"
            }
        },
        "llvm": {
            "remote": {
                "id": "apple/swift-llvm"
            }
        },
        "swift-xcode-playground-support": {
            "remote": {
                "id": "apple/swift-xcode-playground-support"
            }
        },
        "swift-corelibs-foundation": {
            "remote": {
                "id": "apple/swift-corelibs-foundation"
            }
        },
        "clang": {
            "remote": {
                "id": "apple/swift-clang"
            }
        },
        "llbuild": {
            "remote": {
                "id": "apple/swift-llbuild"
            }
        },
        "cmark": {
            "remote": {
                "id": "apple/swift-cmark"
            }
        },
        "lldb": {
            "remote": {
                "id": "apple/swift-lldb"
            }
        },
        "swift-corelibs-xctest": {
            "remote": {
                "id": "apple/swift-corelibs-xctest"
            }
        },
        "ninja": {
            "remote": {
                "id": "ninja-build/ninja"
            }
        },
        "swift-integration-tests": {
            "remote": {
                "id": "apple/swift-integration-tests"
            }
        },
        "swiftpm": {
            "remote": {
                "id": "apple/swift-package-manager"
            }
        },
        "swift": {
            "remote": {
                "id": "apple/swift"
            }
        },
        "swift-corelibs-libdispatch": {
            "remote": {
                "id": "apple/swift-corelibs-libdispatch"
            }
        }
    },
    "branch-schemes": {
        "utf8string": {
            "repos": {
                "compiler-rt": "cd84712c809bdad9815b133a1423d0ed244d79dd",
                "llvm": "6d629af647e6081509f2b7b37f0dd3356ebc7f10",
                "swift-xcode-playground-support": "f2e299a37eb6531918b6c9ce7f555b54d68d92d4",
                "swift-corelibs-foundation": "9f217d195dc115cb82442ee0d8eba1027f3d6f8f",
                "clang": "257fa1914346d3a1d53a0d8d8f15f5a80cd47dc9",
                "llbuild": "e613180370e85b4a1cc25c579b8a4ca224f3e729",
                "cmark": "d875488a6a95d5487b7c675f79a8dafef210a65f",
                "lldb": "dc5868b38689066c392bcee2005fa07c99c25949",
                "swift-syntax": "0144a2b1adec478d7be341b1108f0089f19ad6a7",
                "swiftpm": "db85546f5178fe62f4ed87fdebead1f0bf2944c1",
                "swift-corelibs-xctest": "d257acf2100582bf9ccdcf50196b4bf3886ea3b3",
                "ninja": "253e94c1fa511704baeb61cf69995bbf09ba435e",
                "swift-integration-tests": "6cfcfc91fa986a82588680bbcd011eacaaf1400b",
                "swift": "$swift_sha",
                "swift-corelibs-libdispatch": "6162a1d17948502cbe0576058d19e095ef3ad8c7"
            },
            "aliases": [
                "utf8string"
            ]
        }
    }
}
EOF

(
cd "$swift_dir"
utils/update-checkout --config="$tmpfile" --scheme=utf8string
)

rm "$tmpfile"

echo OK
